#!/usr/bin/env sh

docker-compose -f docker-compose.yaml -f docker-compose.override.yaml down -v
docker-compose -f docker-compose.yaml -f docker-compose.override.yaml build --no-cache
docker-compose -f docker-compose.yaml -f docker-compose.override.yaml up --force-recreate
